# Generated by Django 5.1.7 on 2025-03-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0002_alter_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='User_Image',
            field=models.ImageField(blank=True, upload_to='items/'),
        ),
    ]
