# Generated by Django 5.1.7 on 2025-03-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_feedback_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='Person_Number',
            new_name='Total_Person',
        ),
    ]
