# Generated by Django 5.1.7 on 2025-03-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_rename_person_number_booktable_total_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Feedback_Description',
            field=models.TextField(max_length=55),
        ),
    ]
